{% set name = "otpauth" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/otpauth-{{ version }}.tar.gz
  sha256: 24f41509f9b99c2fd8aef386eefe3a2d58b7601ec23d4af41c487bcee3954359

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - otpauth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lepture/otpauth
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implements two-step verification of HOTP/TOTP
  description: |
    otpauth is One Time Password Authentication, which is usually called
    as two steps verification. You may have heard it from Google, Dropbox
    and etc.
  doc_url: https://pythonhosted.org/otpauth/
  dev_url: https://github.com/lepture/otpauth

extra:
  recipe-maintainers:
    - jan-janssen
