{% set name = "otpauth" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/otpauth-{{ version }}.tar.gz
  sha256: 12fdae64d0664ffbfafdadfdc1ec8fe571acd0e71a62f79233dd3bda088d39c2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}

test:
  imports:
    - otpauth
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lepture/otpauth
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implements two-step verification of HOTP/TOTP
  description: |
    otpauth is One Time Password Authentication, which is usually called
    as two steps verification. You may have heard it from Google, Dropbox
    and etc.
  doc_url: https://pythonhosted.org/otpauth/
  dev_url: https://github.com/lepture/otpauth

extra:
  recipe-maintainers:
    - jan-janssen
